CREATE TABLE roles (
	id_role INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE flavors (
	id_flavor INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR (100),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE containers (
	id_container INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR (100) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE products (
	id_product INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR (100) NOT NULL UNIQUE,
	price DECIMAL(10,2),
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE customers (
	id_customer INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	first_name VARCHAR (100) NOT NULL,
	last_name VARCHAR (100) NOT NULL,
	document_number VARCHAR (50),
	phone_number VARCHAR(20),
	address VARCHAR (255),
	email VARCHAR (100) UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users (
	id_user INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	role_id INT,
	first_name VARCHAR (100) NOT NULL,
	last_name VARCHAR (100) NOT NULL,
	document_number VARCHAR (50) NOT NULL,
	phone_number VARCHAR(20) NOT NULL UNIQUE,
	address VARCHAR (255) NOT NULL,
	email VARCHAR (100) NOT NULL UNIQUE,
	password VARCHAR (255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	FOREIGN KEY (role_id) REFERENCES roles (id_role) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE invoices (
	id_invoice INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	user_id INT NOT NULL,
	customer_id INT NOT NULL,
	date_time DATETIME NOT NULL,
	total DECIMAL(18,4),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	FOREIGN KEY (user_id) REFERENCES users (id_user) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (customer_id) REFERENCES customers (id_customer) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE invoice_items (
	id_invoice_item INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	invoice_id INT NOT NULL,
	product_id INT NOT NULL,
	flavor_id INT NOT NULL,
	item_group INT NOT NULL,
	balls_quantity INT NOT NULL,
	price_unit DECIMAL(10,2),
	subtotal DECIMAL(14,2),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	FOREIGN KEY (invoice_id) REFERENCES invoices (id_invoice) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (product_id) REFERENCES products (id_product) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (flavor_id) REFERENCES flavors (id_flavor) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE inventory (
    id_inventory INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    flavor_id INT,
    container_id INT,
    quantity INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (flavor_id) REFERENCES flavors (id_flavor) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (container_id) REFERENCES containers (id_container) ON DELETE SET NULL ON UPDATE CASCADE,
    
    CONSTRAINT chk_one_fk_not_null CHECK (
        (flavor_id IS NOT NULL AND container_id IS NULL) OR
        (flavor_id IS NULL AND container_id IS NOT NULL)
    )
);